channel: retry ssh_channel_open_session with SSH_AGAIN
Setting a low SSH options timeout value can lead to

LibsshChannelException: Failed to open_session: [-2]

Attempt to retry when this occurs.

(cherry picked from commit fe1f81bab247d883147ffa9ed0618414c6aa0821)